Repository SoFastCar/sofastcar-iOS, pull requests merged in 2020-09, with the labels that each got.

#25 bug: 회원가입 및 로그인 페이지 warning 제거
  sofastcar/sofastcar/ViewController/Login/CardEnrollVC.swift
  sofastcar/sofastcar/ViewController/Login/DefualtUserInfoVC.swift
  sofastcar/sofastcar/ViewController/Login/DriverLicenseEnrollinitVC.swift
  sofastcar/sofastcar/ViewController/Login/SingUpCompleteVC.swift
  sofastcar/sofastcar/ViewController/Login/TosVC.swift
Labels: bug, enhancement

#27 대여화면 메인
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/SampleCar.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/SampleCar.imageset/pngwing.com.png
  sofastcar/sofastcar/Assets.xcassets/Reservation/Contents.json
  sofastcar/sofastcar/Info.plist
  sofastcar/sofastcar/Utility/CommonUI.swift
  sofastcar/sofastcar/View/Reservation/ReservationStateView.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationDashboardVC.swift
Labels: enhancement

#33 feat: 회원가입시 핸드폰 인증 로직 추가
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar.xcworkspace/xcshareddata/swiftpm/Package.resolved
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Assets.xcassets/Resercation/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Resercation/testCar.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Resercation/testCar.imageset/testCar.png
  sofastcar/sofastcar/Custom/Login/LoginCompleteButton.swift
  sofastcar/sofastcar/Model/Login/PhoneAuthResponse.swift
  sofastcar/sofastcar/Model/Login/SignUpUserData.swift
  sofastcar/sofastcar/Model/SignUpUserData.swift
  sofastcar/sofastcar/Utility/CommonUI.swift
  sofastcar/sofastcar/View/Login/UserAuthScrollView.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmCustomCell.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmTableHeaderView.swift
  sofastcar/sofastcar/ViewController/Login/SingUpCompleteVC.swift
  sofastcar/sofastcar/ViewController/Login/TouVC.swift
  sofastcar/sofastcar/ViewController/Login/UserAuthVC.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
Labels: enhancement

#35 feat: 회원가입 API 연동
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Info.plist
  sofastcar/sofastcar/View/Login/DefaultUserInfoView.swift
  sofastcar/sofastcar/View/Login/UserAuthScrollView.swift
  sofastcar/sofastcar/ViewController/Login/CheckDriverLicenseVC.swift
  sofastcar/sofastcar/ViewController/Login/DefualtUserInfoVC.swift
  sofastcar/sofastcar/ViewController/Login/SocarPassVC.swift
  sofastcar/sofastcar/ViewController/Login/UserAuthVC.swift
Labels: enhancement

#36 Develop a03
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Assets.xcassets/Main/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Main/NMF/mSNormalBlue.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Main/NMF/mSNormalBlue.imageset/mSNormalBlue.png
  sofastcar/sofastcar/Assets.xcassets/Main/NMF/mSNormalBlue.imageset/mSNormalBlue@2x.png
  sofastcar/sofastcar/Assets.xcassets/Main/NMF/mSNormalBlue.imageset/mSNormalBlue@3x.png
  sofastcar/sofastcar/Assets.xcassets/Main/UserInterface/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Main/UserInterface/icons8-left-50.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Main/UserInterface/icons8-left-50.imageset/icons8-left-50.png
  sofastcar/sofastcar/Assets.xcassets/Main/UserInterface/icons8-menu-rounded-50.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Main/UserInterface/icons8-menu-rounded-50.imageset/icons8-menu-rounded-50.png
  sofastcar/sofastcar/Assets.xcassets/icons8-menu-24.png
  sofastcar/sofastcar/View/CarListView.swift
  sofastcar/sofastcar/View/SearchView.swift
  sofastcar/sofastcar/View/TopSearchView.swift
  sofastcar/sofastcar/View/TopView.swift
  sofastcar/sofastcar/ViewController/MainVC.swift
  sofastcar/sofastcar/ViewController/SearchResultTableVC.swift
  sofastcar/sofastcar/ViewController/SearchVC.swift
Labels: enhancement

#37 feat: Login API Connet, Save User Tocken
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Utility/UserDefault.swift
  sofastcar/sofastcar/ViewController/Login/LoginVC.swift
Labels: enhancement

#38 [대여/반납] 스마트키 화면 구현 완료
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Utility/CommonUI.swift
  sofastcar/sofastcar/View/Reservation/CarKeyView.swift
  sofastcar/sofastcar/View/Reservation/ReservationStateView.swift
  sofastcar/sofastcar/ViewController/Reservation/CarKeyViewController.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationDashboardVC.swift
Labels: enhancement

#41 fix: ReservationDashboardVC fix UI constraints
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/View/Main/TopView.swift
  sofastcar/sofastcar/View/Reservation/CarKeyView.swift
  sofastcar/sofastcar/View/Reservation/ReservationStateView.swift
  sofastcar/sofastcar/ViewController/Reservation/CarKeyVC.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationDashboardVC.swift
Labels: bug

#44 feat: 대여 정보 확인 뷰 생성
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Custom/Main/LeftAlignedCollectionViewFlowLayout.swift
  sofastcar/sofastcar/Model/Main/Insure.swift
  sofastcar/sofastcar/Utility/CommonUI.swift
  sofastcar/sofastcar/Utility/Extension.swift
  sofastcar/sofastcar/Utility/Protocol.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmCVCell.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmCustomCell.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmTableHeaderView.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
Labels: enhancement

#50 feat: 결제 정보 확인 화면 구현
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Custom/Login/CompleteButton.swift
  sofastcar/sofastcar/Model/Main/Insurance.swift
  sofastcar/sofastcar/Utility/CommonUI.swift
  sofastcar/sofastcar/Utility/Protocol.swift
  sofastcar/sofastcar/View/Login/CardEnrollView.swift
  sofastcar/sofastcar/View/Login/CheckDriverLicenseView.swift
  sofastcar/sofastcar/View/Login/DefaultUserInfoView.swift
  sofastcar/sofastcar/View/Login/DriverLicenseEnrollinitView.swift
  sofastcar/sofastcar/View/Login/TouView.swift
  sofastcar/sofastcar/View/Login/UserAuthScrollView.swift
  sofastcar/sofastcar/View/Main/PaymentConfirmCell.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmCustomCell.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmTableHeaderView.swift
  sofastcar/sofastcar/ViewController/Login/SingUpCompleteVC.swift
  sofastcar/sofastcar/ViewController/Main/PaymentConfirmTableVC.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
Labels: enhancement

#52 feat: 차량 확인하기 UI
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Utility/CommonUI.swift
  sofastcar/sofastcar/View/Reservation/LeftAlignedCollectionViewFlowLayout.swift
  sofastcar/sofastcar/View/Reservation/ReservationStateView.swift
  sofastcar/sofastcar/View/Reservation/TagCollectionViewCell.swift
  sofastcar/sofastcar/View/Reservation/VehicleCheckView.swift
  sofastcar/sofastcar/ViewController/Reservation/CarKeyVC.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationDashboardVC.swift
  sofastcar/sofastcar/ViewController/Reservation/VehicleCheckVC.swift
Labels: enhancement

#56 feat: 차량 확인하기 UI 디테일
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Utility/Extension.swift
  sofastcar/sofastcar/View/Reservation/LeftAlignedTagCollectionViewFlowLayout.swift
  sofastcar/sofastcar/View/Reservation/TagCollectionViewCell.swift
  sofastcar/sofastcar/View/Reservation/VehicleCheckView.swift
  sofastcar/sofastcar/ViewController/Reservation/VehicleCheckVC.swift
Labels: enhancement

#58 차량 대여 정보 화면 구현 #51
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Utility/Protocol.swift
  sofastcar/sofastcar/View/Main/PaymentConfirmCell.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmCustomCell.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmTableHeaderView.swift
  sofastcar/sofastcar/View/Reservation/ReservationDetailHeader.swift
  sofastcar/sofastcar/View/Reservation/ReservationEtcCell.swift
  sofastcar/sofastcar/View/Reservation/ReservationPaymentCell.swift
  sofastcar/sofastcar/View/Reservation/ReservationRentalInfoCell.swift
  sofastcar/sofastcar/ViewController/Main/PaymentConfirmTableVC.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationDetailTableVC.swift
Labels: enhancement

#62 1차 통합 테스트
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Custom/Main/RentReturnTimeButton.swift
  sofastcar/sofastcar/Custom/Main/SetBookingTimeButton.swift
  sofastcar/sofastcar/Utility/Extension.swift
  sofastcar/sofastcar/Utility/UserDefault.swift
  sofastcar/sofastcar/ViewController/Login/UserAuthVC.swift
Labels: enhancement

#66 docs: Time 관련 코멘트 추가
  sofastcar/sofastcar/Utility/Time.swift
Labels: documentation

#68 feat: 외관 촬영 UI 1차
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/보조석뒷면.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/보조석뒷면.imageset/보조석뒷면.png
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/보조석앞면.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/보조석앞면.imageset/보조석앞면.png
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/운전석뒷면.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/운전석뒷면.imageset/운전석뒷면.png
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/운전석앞면.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/운전석앞면.imageset/운전석앞면.png
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/전면.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/전면.imageset/전면.png
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/후면.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/후면.imageset/후면.png
  sofastcar/sofastcar/Utility/CommonUI.swift
  sofastcar/sofastcar/View/Reservation/MenuCollectionViewCell.swift
  sofastcar/sofastcar/View/Reservation/VehicleCheckView.swift
  sofastcar/sofastcar/View/Reservation/VehicleTakePictureImageView.swift
  sofastcar/sofastcar/View/Reservation/VehicleTakePictureMenuView.swift
  sofastcar/sofastcar/View/Reservation/VehicleTakePictureView.swift
  sofastcar/sofastcar/ViewController/Reservation/VehicleCheckVC.swift
  sofastcar/sofastcar/ViewController/Reservation/VehicleTakePictureVC.swift
Labels: enhancement

#69 merge: fix image warning
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/Image.imageset/Contents.json
Labels: bug

#74 차량 파손 이중 체크 UI
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Assets.xcassets/Reservation/CarCheck/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/CarCheck/깨짐.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/CarCheck/깨짐.imageset/깨짐.png
  sofastcar/sofastcar/Assets.xcassets/Reservation/CarCheck/스크래치.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/CarCheck/스크래치.imageset/스크래치.png
  sofastcar/sofastcar/Assets.xcassets/Reservation/CarCheck/이격.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/CarCheck/이격.imageset/이격.png
  sofastcar/sofastcar/Assets.xcassets/Reservation/CarCheck/찌그러짐.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/CarCheck/찌그러짐.imageset/찌그러짐.png
  sofastcar/sofastcar/Utility/Extension.swift
  sofastcar/sofastcar/View/Reservation/VehicleCheckCell.swift
  sofastcar/sofastcar/View/Reservation/VehicleDoubleCheckView.swift
  sofastcar/sofastcar/ViewController/Reservation/VehicleDoubleCheckVC.swift
  sofastcar/sofastcar/ViewController/Reservation/VehicleTakePictureVC.swift
Labels: enhancement

#77 Develop
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Custom/Main/InsuranceMenuItemButton.swift
  sofastcar/sofastcar/Custom/Main/SetBookingTimeButton.swift
  sofastcar/sofastcar/Model/Main/SocarListData.swift
  sofastcar/sofastcar/Model/Main/SocarZoneData.swift
  sofastcar/sofastcar/Utility/EndPoint.swift
  sofastcar/sofastcar/Utility/SocaZoneProvidable.swift
  sofastcar/sofastcar/Utility/SocarZoneProvider.swift
  sofastcar/sofastcar/View/Main/CarListTableViewCell.swift
  sofastcar/sofastcar/View/Main/CarListView.swift
  sofastcar/sofastcar/View/Main/InsuranceMenuHeaderView.swift
  sofastcar/sofastcar/View/Main/InsuranceMenuView.swift
  sofastcar/sofastcar/ViewController/Main/BookingTimeVC.swift
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
Labels: enhancement

#82 feat: 예약하기 뷰 연동 준비
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Assets.xcassets/Main/Markers/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Main/Markers/callPointMarker1.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Main/Markers/callPointMarker1.imageset/callPointMarker1.png
  sofastcar/sofastcar/Assets.xcassets/Main/Markers/socarRentMarker.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Main/Markers/socarRentMarker.imageset/socarRentMarker.png
  sofastcar/sofastcar/Assets.xcassets/Main/Markers/socarZoneMarker.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Main/Markers/socarZoneMarker.imageset/socarZoneMarker.png
  sofastcar/sofastcar/Custom/Main/InsuranceMenuItemButton.swift
  sofastcar/sofastcar/Custom/Main/SetBookingTimeButton.swift
  sofastcar/sofastcar/Model/Main/InsuranceData.swift
  sofastcar/sofastcar/Model/Main/SocarListData.swift
  sofastcar/sofastcar/View/Main/InsuranceMenuView.swift
  sofastcar/sofastcar/ViewController/Main/BookingTimeVC.swift
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
Labels: documentation, enhancement

#86 resevationConfirmTableVC 예약연동뷰 관련 설정 변경
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Model/Main/SocarListData.swift
  sofastcar/sofastcar/Utility/Time.swift
  sofastcar/sofastcar/View/Reservation/ReservationConfirmCustomCell.swift
  sofastcar/sofastcar/View/Reservation/ReservationConfirmTableHeaderView.swift
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationConfirmTableVC.swift
Labels: enhancement

#88 차량 파손 확인 완료 후 UI
  sofastcar/sofastcar/Assets.xcassets/Main/NMF/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Main/NMF/mSNormalBlue.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Main/NMF/mSNormalBlue.imageset/mSNormalBlue.png
  sofastcar/sofastcar/Assets.xcassets/Main/NMF/mSNormalBlue.imageset/mSNormalBlue@2x.png
  sofastcar/sofastcar/Assets.xcassets/Main/NMF/mSNormalBlue.imageset/mSNormalBlue@3x.png
  sofastcar/sofastcar/Assets.xcassets/Main/NMF/mSNormalBlue.imageset/pin-1.png
  sofastcar/sofastcar/Assets.xcassets/Main/NMF/mSNormalBlue.imageset/pin-2.png
  sofastcar/sofastcar/Assets.xcassets/Main/NMF/mSNormalBlue.imageset/pin.png
  sofastcar/sofastcar/Utility/UserDefault.swift
  sofastcar/sofastcar/View/Reservation/VehicleCheckView.swift
  sofastcar/sofastcar/View/Reservation/VehicleDoubleCheckView.swift
  sofastcar/sofastcar/ViewController/Reservation/VehicleDoubleCheckVC.swift
Labels: enhancement

#90 회원가입 API 수정 / UIImageView 커스텀 추가
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Custom/CustomImageView.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmCustomCell.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmTableHeaderView.swift
  sofastcar/sofastcar/ViewController/Login/DefualtUserInfoVC.swift
  sofastcar/sofastcar/ViewController/Login/LoginVC.swift
  sofastcar/sofastcar/ViewController/Login/SingUpCompleteVC.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
Labels: bug, enhancement

#92 차량 확인하기 -> 반납 메인 화면 전환
  sofastcar/sofastcar/Utility/UserDefault.swift
  sofastcar/sofastcar/View/Reservation/ReservationStateView.swift
  sofastcar/sofastcar/View/Reservation/VehicleCheckView.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationDashboardVC.swift
  sofastcar/sofastcar/ViewController/Reservation/VehicleCheckVC.swift
Labels: enhancement

#94 feat: Error Resolve
  sofastcar/sofastcar/View/Main/ReservationConfirmTableHeaderView.swift
  sofastcar/sofastcar/ViewController/Main/BookingTimeVC.swift
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
  sofastcar/sofastcar/ViewController/Main/PaymentConfirmTableVC.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
Labels: bug, enhancement

#95 차량 확인하기 버튼 레이아웃 갱신
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/보조석뒷면.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/Car/보조석앞면.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/CarCheck/깨짐.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/CarCheck/스크래치.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Reservation/CarCheck/이격.imageset/Contents.json
  sofastcar/sofastcar/View/Reservation/VehicleCheckView.swift
  sofastcar/sofastcar/ViewController/Reservation/VehicleCheckVC.swift
Labels: bug

#102 feat: 보험 선택 화면 VC 분리
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Assets.xcassets/Login/SingupInitVC/SingupStarter.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/Login/SingupInitVC/SingupStarter.imageset/SingupStarter.png
  sofastcar/sofastcar/Custom/Main/SetBookingTimeButton.swift
  sofastcar/sofastcar/Utility/Time.swift
  sofastcar/sofastcar/Utility/UserDefault.swift
  sofastcar/sofastcar/View/Main/InsuranceMenuView.swift
  sofastcar/sofastcar/ViewController/Common/InsurancePopVC.swift
  sofastcar/sofastcar/ViewController/Main/BookingTimeVC.swift
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
  sofastcar/sofastcar/ViewController/Main/PaymentConfirmTableVC.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
Labels: enhancement

#103 대여 메인 화면 연동 구현
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Utility/UserDefault.swift
  sofastcar/sofastcar/ViewController/Login/LoginVC.swift
  sofastcar/sofastcar/ViewController/Main/PaymentConfirmTableVC.swift
  sofastcar/sofastcar/ViewController/Main/SearchVC.swift
Labels: enhancement

#106 대여 정보 화면 구현 디테일 및 반납 화면 전환 뷰
  sofastcar/sofastcar/Utility/CommonUI.swift
  sofastcar/sofastcar/View/Reservation/ReservationStateView.swift
Labels: bug, enhancement

#112 스마트키 버튼 액션
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/View/Reservation/CarKeyView.swift
  sofastcar/sofastcar/ViewController/Reservation/CarKeyViewController.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationDashboardVC.swift
Labels: bug

#116 차량 정보 가격 변경을 위한 데이터 셋 연동 및 인덱스 생성
  sofastcar/sofastcar/Model/Main/SocarListData.swift
  sofastcar/sofastcar/Utility/Time.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmCustomCell.swift
  sofastcar/sofastcar/ViewController/Common/InsurancePopVC.swift
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
Labels: enhancement

#117 bug: Login Error Resolve
  sofastcar/sofastcar/ViewController/Login/LoginVC.swift
Labels: bug

#120 차량 예약 가격 및 주행요금 표시 설정
  sofastcar/sofastcar/Utility/Extension.swift
  sofastcar/sofastcar/View/Main/PaymentConfirmCell.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmCustomCell.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmTableHeaderView.swift
  sofastcar/sofastcar/ViewController/Main/BookingTimeVC.swift
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
  sofastcar/sofastcar/ViewController/Main/PaymentConfirmTableVC.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
Labels: bug, enhancement

#121 메인 뷰 시간 라벨 수정
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Custom/Main/SetBookingTimeButton.swift
  sofastcar/sofastcar/Utility/Time.swift
  sofastcar/sofastcar/ViewController/Main/BookingTimeVC.swift
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
Labels: bug

#122 feat: Reservation Cost Calculation Error Resolve
  sofastcar/sofastcar/Utility/Extension.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
Labels: bug

#123 Develop(중간발표 최종)
  sofastcar/sofastcar/Custom/Main/SearchCustomButton.swift
  sofastcar/sofastcar/Custom/Main/SetBookingTimeButton.swift
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
Labels: enhancement

#124 README.md 및 이미지 작업, 발표준비
  README.md
  images/LOGIN.gif
  images/MAIN.gif
  images/RANTAL.gif
  images/activePin.png
  images/logo.png
  images/logo.psd
  images/long_logo.png
  images/long_logo.psd
  images/pin.png
  images/pinfile.psd
  images/samplecar.png
  images/깨짐.png
  images/스크래치.png
  images/이격.png
  images/찌그러짐.png
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/ViewController/Reservation/ReservationDashboardVC.swift
Labels: documentation, enhancement

#128 일부 화면 개선
  sofastcar/Pods/Pods.xcodeproj/project.pbxproj
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar.xcodeproj/xcshareddata/xcschemes/sofastcar.xcscheme
  sofastcar/sofastcar/Custom/Main/InsuranceMenuItemButton.swift
  sofastcar/sofastcar/View/Common/BookingTimeCell.swift
  sofastcar/sofastcar/View/Common/InsuranceMenuHeaderView.swift
  sofastcar/sofastcar/View/Common/InsuranceMenuView.swift
  sofastcar/sofastcar/View/Main/PaymentConfirmCell.swift
  sofastcar/sofastcar/View/Main/ReservationConfirmCustomCell.swift
  sofastcar/sofastcar/ViewController/Common/BookingTimeVC.swift
  sofastcar/sofastcar/ViewController/Common/InsurancePopVC.swift
  sofastcar/sofastcar/ViewController/Main/PaymentConfirmTableVC.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
Labels: Refactoring

#134 예약상세정보 뷰 연동 및 일부 뷰 오류 수정
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Model/Main/Reservation.swift
  sofastcar/sofastcar/View/Main/RentHistoryCell.swift
  sofastcar/sofastcar/View/Reservation/ReservationDetailHeader.swift
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
  sofastcar/sofastcar/ViewController/Main/PaymentConfirmTableVC.swift
  sofastcar/sofastcar/ViewController/Main/RentHistoryVC.swift
  sofastcar/sofastcar/ViewController/Main/SideBarVC.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationDetailTableVC.swift
Labels: bug, feature

#136 bug: 사용사가 선택한 시간 PickerView 값 정상 표현
  sofastcar/sofastcar/Utility/Time.swift
  sofastcar/sofastcar/ViewController/Common/BookingTimeVC.swift
Labels: bug

#137 반납(차량상태 확인) 화면
  README.md
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Utility/CommonUI.swift
  sofastcar/sofastcar/Utility/Extension.swift
  sofastcar/sofastcar/View/Reservation/ReturnVehicleStatusView.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationDashboardVC.swift
  sofastcar/sofastcar/ViewController/Reservation/ReturnVehicleStatusVC.swift
Labels: feature

#141 쏘카존 상세정보 보기화면 구현 및 사이드바 오류 수정
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Utility/Extension.swift
  sofastcar/sofastcar/Utility/Protocol.swift
  sofastcar/sofastcar/View/Common/BookingTimeCell.swift
  sofastcar/sofastcar/View/Common/DetailSocarZoneInfoCell.swift
  sofastcar/sofastcar/View/Main/PaymentConfirmCell.swift
  sofastcar/sofastcar/View/Main/SideBarHeaderView.swift
  sofastcar/sofastcar/View/Reservation/ReservationPaymentCell.swift
  sofastcar/sofastcar/View/Reservation/ReservationRentalInfoCell.swift
  sofastcar/sofastcar/ViewController/Common/BookingTimeVC.swift
  sofastcar/sofastcar/ViewController/Common/DetailSocarZoneInfoVC.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
  sofastcar/sofastcar/ViewController/Main/SideBarVC.swift
Labels: bug, feature

#142 예약시간 수정 관련 버그 수정
  sofastcar/sofastcar/Custom/Main/SetBookingTimeButton.swift
  sofastcar/sofastcar/Utility/Extension.swift
  sofastcar/sofastcar/Utility/Time.swift
  sofastcar/sofastcar/View/Main/RentHistoryCell.swift
  sofastcar/sofastcar/View/Reservation/ReservationDetailHeader.swift
  sofastcar/sofastcar/View/Reservation/ReservationPaymentCell.swift
  sofastcar/sofastcar/View/Reservation/ReservationRentalInfoCell.swift
  sofastcar/sofastcar/ViewController/Common/BookingTimeVC.swift
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
  sofastcar/sofastcar/ViewController/Main/RentHistoryVC.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationDetailTableVC.swift
Labels: bug

#144 feat: 예약하기에서 뒤로가기 시, 이용시간 버튼 팝업되는 문제 해결
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
  sofastcar/sofastcar/ViewController/Main/ReservationConfirmTableVC.swift
Labels: bug

#146 예약시간 초과 시 경고 메시지
  sofastcar/sofastcar/Custom/Login/CompleteButton.swift
  sofastcar/sofastcar/ViewController/Common/BookingTimeVC.swift
Labels: bug, feature

#150 feat: 검색 기능 추가
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Model/Main/GlobalVariables.swift
  sofastcar/sofastcar/Model/Main/NMFData.swift
  sofastcar/sofastcar/Model/Main/NMapAddress.swift
  sofastcar/sofastcar/View/Main/SearchResultTableViewCell.swift
  sofastcar/sofastcar/ViewController/Main/MainVC.swift
  sofastcar/sofastcar/ViewController/Main/SearchVC.swift
Labels: feature

#148 반납 (반납하기) 화면
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Utility/CommonUI.swift
  sofastcar/sofastcar/View/Reservation/CheckButtonView.swift
  sofastcar/sofastcar/View/Reservation/ReturnVehicleView.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationDashboardVC.swift
  sofastcar/sofastcar/ViewController/Reservation/ReturnVehicleStatusVC.swift
  sofastcar/sofastcar/ViewController/Reservation/ReturnVehicleVC.swift
Labels: feature

#151 카드 및 운전면허증 인식 뷰 생성
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/View/Login/CustomCameraView.swift
  sofastcar/sofastcar/ViewController/Login/CustomCameraVC.swift
  sofastcar/sofastcar/ViewController/Login/DriverLicenseEnrollinitVC.swift
Labels: feature

#159 사용자 디테일 사이드 바 메뉴 구현
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/View/SideBar/RentHistoryCell.swift
  sofastcar/sofastcar/View/SideBar/SideBarBottonView.swift
  sofastcar/sofastcar/View/SideBar/SideBarCustomCell.swift
  sofastcar/sofastcar/View/SideBar/SideBarHeaderView.swift
  sofastcar/sofastcar/View/SideBar/UserDetailCell.swift
  sofastcar/sofastcar/ViewController/SideBar/RentHistoryVC.swift
  sofastcar/sofastcar/ViewController/SideBar/SideBarVC.swift
  sofastcar/sofastcar/ViewController/SideBar/UserDetailVC.swift
Labels: feature

#160 반납(반납 후 상태) 화면
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Utility/Extension.swift
  sofastcar/sofastcar/View/Reservation/ReturnVehicleView.swift
  sofastcar/sofastcar/View/Reservation/UserStatusAfterReturnView.swift
  sofastcar/sofastcar/ViewController/Reservation/ReturnVehicleVC.swift
  sofastcar/sofastcar/ViewController/Reservation/UserStatusAfterReturnVC.swift
Labels: feature

#162 사이드바 - 로그아웃 기능 추가
  sofastcar/sofastcar/Utility/Protocol.swift
  sofastcar/sofastcar/Utility/UserDefault.swift
  sofastcar/sofastcar/View/SideBar/UserDetailCell.swift
  sofastcar/sofastcar/ViewController/SideBar/UserDetailVC.swift
Labels: feature

#163 쏘카 클럽 화면 구현
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Custom/DotsLineView.swift
  sofastcar/sofastcar/Custom/SideBar/CouponView.swift
  sofastcar/sofastcar/View/SideBar/SideBarHeaderView.swift
  sofastcar/sofastcar/View/SideBar/SocarClubScrollView.swift
  sofastcar/sofastcar/ViewController/SideBar/SideBarVC.swift
  sofastcar/sofastcar/ViewController/SideBar/SocarClubVC.swift
  sofastcar/sofastcar/ViewController/SideBar/UserDetailVC.swift
Labels: feature

#167 feat: 사이드바 쏘카클럽 화면 수정
  sofastcar/SocarClub.mov
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/AppDelegate.swift
  sofastcar/sofastcar/Assets.xcassets/SideBar/Contents.json
  sofastcar/sofastcar/Assets.xcassets/SideBar/SocarClub.dataset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/SideBar/SocarClub.dataset/SocarClub.mov
  sofastcar/sofastcar/Custom/SideBar/CouponView.swift
  sofastcar/sofastcar/Model/Login/SignUpUserData.swift
  sofastcar/sofastcar/Model/SideBar/Coupon.swift
  sofastcar/sofastcar/View/Login/DefaultUserInfoView.swift
  sofastcar/sofastcar/View/SideBar/SocarClubScrollView.swift
  sofastcar/sofastcar/ViewController/Login/DefualtUserInfoVC.swift
  sofastcar/sofastcar/ViewController/Login/TouVC.swift
  sofastcar/sofastcar/ViewController/Login/UserAuthVC.swift
  sofastcar/sofastcar/ViewController/SideBar/SocarClubVC.swift
Labels: feature

#168 feat: 쏘카클럽 화면 일부 수정
  sofastcar/sofastcar/Custom/SideBar/CouponView.swift
  sofastcar/sofastcar/View/SideBar/SocarClubScrollView.swift
  sofastcar/sofastcar/ViewController/SideBar/SocarClubVC.swift
Labels: feature

#169 feat: 이벤트 혜택 뷰 완성
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Assets.xcassets/SideBar/EventAndBenefit/Contents.json
  sofastcar/sofastcar/Assets.xcassets/SideBar/EventAndBenefit/Event1.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/SideBar/EventAndBenefit/Event1.imageset/Event1.png
  sofastcar/sofastcar/Assets.xcassets/SideBar/EventAndBenefit/Event2.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/SideBar/EventAndBenefit/Event2.imageset/Event2.png
  sofastcar/sofastcar/Assets.xcassets/SideBar/EventAndBenefit/Event3.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/SideBar/EventAndBenefit/Event3.imageset/Event3.png
  sofastcar/sofastcar/Assets.xcassets/SideBar/EventAndBenefit/vip.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/SideBar/EventAndBenefit/vip.imageset/vip.png
  sofastcar/sofastcar/Model/SideBar/EventBenifits.swift
  sofastcar/sofastcar/Utility/Extension.swift
  sofastcar/sofastcar/View/SideBar/EventAndBenefitFooterView.swift
  sofastcar/sofastcar/View/SideBar/EventAndBenefitsCell.swift
  sofastcar/sofastcar/ViewController/SideBar/EventAndBenefitsVC.swift
  sofastcar/sofastcar/ViewController/SideBar/SideBarVC.swift
Labels: feature

#170 feat: 친구 초대 화면 구현 완료
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Assets.xcassets/SideBar/FriendsInvite/Contents.json
  sofastcar/sofastcar/Assets.xcassets/SideBar/FriendsInvite/kakao_Invite.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/SideBar/FriendsInvite/kakao_Invite.imageset/kakao_Invite.png
  sofastcar/sofastcar/Assets.xcassets/SideBar/FriendsInvite/share_Invite.imageset/Contents.json
  sofastcar/sofastcar/Assets.xcassets/SideBar/FriendsInvite/share_Invite.imageset/share_Invite.png
  sofastcar/sofastcar/View/SideBar/FriendsInviteView.swift
  sofastcar/sofastcar/ViewController/SideBar/FriendsInciteVC.swift
  sofastcar/sofastcar/ViewController/SideBar/SideBarVC.swift
Labels: feature

#172 아두이노 스마트키 연결
  sofastcar/sofastcar.xcodeproj/project.pbxproj
  sofastcar/sofastcar/Info.plist
  sofastcar/sofastcar/Utility/CoreBluetoothIO.swift
  sofastcar/sofastcar/Utility/NSData+Int8.swift
  sofastcar/sofastcar/View/Reservation/CarKeyView.swift
  sofastcar/sofastcar/ViewController/Reservation/ReservationDashboardVC.swift
  sofastcar/sofastcar/ViewController/Reservation/UserStatusAfterReturnVC.swift
Labels: feature
